CREATE TABLE MONTH (
    ID INT PRIMARY KEY,
    NAME VARCHAR(160)
);

CREATE TABLE EVENT_PLAN (
    NAME VARCHAR(160),
    MONTH INT REFERENCES MONTH(ID),
    YEAR INT,
    GAME VARCHAR(160) REFERENCES GAMES(NAME)
);

ALTER TABLE EVENT_PLAN
ADD CONSTRAINT name_pkey PRIMARY KEY (NAME);

CREATE TABLE PERSON_EVENTPLAN_AVAILABILITY (
    PersonID Varchar(160) REFERENCES PERSON(NAME),
    EVENTPLANID VARCHAR(160) REFERENCES EVENT_PLAN(NAME),
    WEEK INT,
    DAYHOUR INT REFERENCES AVAILABILITY(ID)
);