CREATE TABLE Event
(
    EventID Int Generated By Default As Identity Primary Key,
    Timestamp Timestamp,
    TimeSpan Varchar(160) References TimeSpan(Name),
    Meal Varchar(160) References Meals(Name),
    Game Varchar(160) References Games(Name),
    Location Varchar(160) References Location(Name),
    Happened Boolean
);

INSERT INTO EVENT (Timestamp, TimeSpan, Meal, Game, Location) VALUES (
                                                                 '2024-10-12 18:00:00',
                                                                 'Saturday from 6:00 PM to 8:00 PM',
                                                                 'Spinach Dip',
                                                                 'Catan',
                                                                 'My Home'
                                                                );

INSERT INTO EVENT (Timestamp, TimeSpan, Game, Location, Happened) VALUES (
                                                                 '2024-11-03 14:00:00',
                                                                 'Sunday from 2:00 PM to 4:00 PM',
                                                                 'Catan',
                                                                 'My Home',
                                                                  True
                                                                );

INSERT INTO EVENT (Timestamp, TimeSpan, Game, Location, Happened, Meal) VALUES (
                                                                 '2024-11-23 14:00:00',
                                                                 'Saturday from 2:00 PM to 4:00 PM',
                                                                 'Catan',
                                                                 'My Home',
                                                                  NULL,
                                                                 NULL
                                                                );

INSERT INTO EVENT (Timestamp, TimeSpan, Game, Location, Happened, Meal) VALUES (
                                                                 '2024-12-07 18:00:00',
                                                                 'Saturday from 6:00 PM to 7:00 PM',
                                                                 'Codenames',
                                                                 'My Home',
                                                                  NULL,
                                                                 NULL
                                                                );



