CREATE TABLE FORMS (
    NAME VARCHAR(160) PRIMARY KEY,
    UPDATED TIMESTAMP
);

CREATE TABLE FORM_REQUESTS (
    Person VARCHAR(160) REFERENCES PERSON(NAME),
    Form VARCHAR(160) REFERENCES FORMS(NAME),
    Timestamp TIMESTAMP
);

CREATE TABLE FORM_SUBMISSIONS (
    Person VARCHAR(160) REFERENCES PERSON(NAME),
    Form VARCHAR(160) REFERENCES FORMS(NAME),
    Timestamp TIMESTAMP
);
